[tool.poetry]
name = 'poetry-demo'
version = '1.0'
description = 'A module used to create beautiful tools and menu for a Python project or program'
authors = ['BlueRed']

[tool.poetry.dependencies]
python = '>=3.6'

[tool.poetry.dev-dependencies]

[build-system]
requires = ['poetry>=0.12']
